python3 automate.py
python3 crlf-attack.py
python3 get-post-loop.py
python3 head-loop.py
python3 http-ua-random.py
python3 http2-ua-multiple-urls.py
python3 lfi-rfi.py
python3 login-attempt-loop.py
python3 login-attempt-single.py
python3 login-attempt-wrong-password.py
python3 login-bruteforce.py
python3 malformed-request.py
python3 request-cookie-ashmalicious.py
python3 scrapper1.py
python3 selenium-auto-feedback.py
python3 selenium-open-feedback.py
python3 selenium-open-feedback2.py
python3 selenium-open-feedback3.py
python3 sqlinjection1.py
python3 ssrf.py
python3 submit_feedback.py
python3 trace-loop.py
python3 traversal.py
python3 traversal2.py
python3 xss-request.py
